#!/usr/bin/env python3
"""
generate_seed.py
Generates `seed.sql` with sample data for the flowers system.

Usage:
  pip install bcrypt
  python generate_seed.py

This script writes `seed.sql` in the same directory. The resulting SQL file
contains INSERT statements with bcrypt-hashed passwords ready to import.
"""
import uuid
import bcrypt
from datetime import date
from pathlib import Path

OUT = Path(__file__).with_name('seed.sql')

def h(passw: str) -> str:
    return bcrypt.hashpw(passw.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

def q(s: str) -> str:
    return s.replace("'", "''")

def main():
    # Sample credentials
    florist_pw = 'floristpass'
    supplier_pw = 'supplierpass'

    # Generate IDs
    uporabnik_f = str(uuid.uuid4())
    uporabnik_s = str(uuid.uuid4())
    cvetlicarna_id = str(uuid.uuid4())
    dobavitelj_id = str(uuid.uuid4())
    roza1 = str(uuid.uuid4())
    roza2 = str(uuid.uuid4())
    narocilo = str(uuid.uuid4())
    postavka = str(uuid.uuid4())
    zgodovina = str(uuid.uuid4())

    # Hash passwords
    h_f = h(florist_pw)
    h_s = h(supplier_pw)

    today = date.today().isoformat()

    parts = []
    parts.append('-- Autogenerated seed SQL')
    parts.append("SET FOREIGN_KEY_CHECKS=0;")
    parts.append('\n-- Users (uporabnik)')
    parts.append("INSERT INTO uporabnik (uporabnik_id, uporabnisko_ime, geslo, e_posta, datum_dodelitve_vloge, vloga, obdobje_veljavnosti) VALUES")
    parts.append("('%s','%s','%s','%s','%s','%s', NULL);" % (uporabnik_f, q('demo_florist'), q(h_f), q('florist@example.com'), today, 'florist'))
    parts.append("('%s','%s','%s','%s','%s','%s', NULL);" % (uporabnik_s, q('demo_supplier'), q(h_s), q('supplier@example.com'), today, 'supplier'))

    parts.append('\n-- Florist (cvetlicarna)')
    parts.append("INSERT INTO cvetlicarna (cvetlicarna_id, uporabnik_id, naziv) VALUES")
    parts.append("('%s','%s','%s');" % (cvetlicarna_id, uporabnik_f, q('Petal & Stem'))) 

    parts.append('\n-- Supplier (dobavitelj)')
    parts.append("INSERT INTO dobavitelj (dobavitelj_id, uporabnik_id, ocena, naziv) VALUES")
    parts.append("('%s','%s', 4.7, '%s');" % (dobavitelj_id, uporabnik_s, q('BloomCo')))

    parts.append('\n-- Roses (roza)')
    parts.append("INSERT INTO roza (roza_id, ime, cena_na_enoto, sezonska_dostopnost, dobavljivost, datum_zacetka_ponudbe, datum_konca_ponudbe, dobavitelj_id) VALUES")
    parts.append("('%s','%s', 2.50, 'Spring', 'In Stock', NULL, NULL, '%s')," % (roza1, q('Pink Rose'), dobavitelj_id))
    parts.append("('%s','%s', 3.75, 'Summer', 'Limited', NULL, NULL, '%s');" % (roza2, q('White Rose'), dobavitelj_id))

    parts.append('\n-- Order (narocilo)')
    parts.append("INSERT INTO narocilo (narocilo_id, datum_narocila, cvetlicarna_id, datum_dostave, status) VALUES")
    parts.append("('%s','%s','%s', NULL, 'pending');" % (narocilo, today, cvetlicarna_id))

    parts.append('\n-- Order item (postavka_narocila)')
    parts.append("INSERT INTO postavka_narocila (postavka_id, narocilo_id, roza_id, kolicina, cena_na_rozo, skupna_vrednost_postavke) VALUES")
    parts.append("('%s','%s','%s', 10, 2.50, 25.00);" % (postavka, narocilo, roza1))

    parts.append('\n-- Order history (zgodovina_narocil)')
    parts.append("INSERT INTO zgodovina_narocil (zgodovina_id, narocilo_id, status, datum_spremembe) VALUES")
    parts.append("('%s','%s','%s','%s');" % (zgodovina, narocilo, 'created', today))

    parts.append('\nSET FOREIGN_KEY_CHECKS=1;')

    OUT.write_text('\n'.join(parts))
    print('Wrote:', OUT)
    print('\nCredentials:')
    print('  florist: demo_florist /', florist_pw)
    print('  supplier: demo_supplier /', supplier_pw)

if __name__ == '__main__':
    main()
